-- =========================
-- CSMS DATABASE SETUP
-- =========================

-- USERS
CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    ROLE_ID NUMBER NOT NULL,
    PHONE VARCHAR2(15),
    CREATED_AT DATE DEFAULT SYSDATE
);

-- ROLES
CREATE TABLE ROLES (
    ROLE_ID NUMBER PRIMARY KEY,
    ROLE_NAME VARCHAR2(20) UNIQUE NOT NULL
);

ALTER TABLE USERS ADD CONSTRAINT FK_USERS_ROLE
FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID);

-- STUDENTS
CREATE TABLE STUDENTS (
    STUDENT_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER UNIQUE NOT NULL,
    DOB DATE NOT NULL,
    GENDER VARCHAR2(10),
    CONDUCT VARCHAR2(20),
    CONDUCT_REMARKS VARCHAR2(200),
    CONSTRAINT CHK_GENDER CHECK (GENDER IN ('Male','Female','Other')),
    CONSTRAINT CHK_CONDUCT CHECK (CONDUCT IN ('Excellent','Good','Average','Poor'))
);

ALTER TABLE STUDENTS ADD CONSTRAINT FK_STUDENT_USER
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

-- TEACHERS
CREATE TABLE TEACHERS (
    TEACHER_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER UNIQUE,
    QUALIFICATION VARCHAR2(100),
    EXPERIENCE NUMBER CHECK (EXPERIENCE >= 0)
);

ALTER TABLE TEACHERS ADD CONSTRAINT FK_TEACHER_USER
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

-- CLASSES
CREATE TABLE CLASSES (
    CLASS_ID NUMBER PRIMARY KEY,
    CLASS_NAME VARCHAR2(20) NOT NULL,
    SECTION VARCHAR2(5) NOT NULL,
    ACADEMIC_YEAR VARCHAR2(10) NOT NULL,
    CONSTRAINT UQ_CLASS UNIQUE (CLASS_NAME, SECTION, ACADEMIC_YEAR)
);

-- SUBJECTS
CREATE TABLE SUBJECTS (
    SUBJECT_ID NUMBER PRIMARY KEY,
    SUBJECT_NAME VARCHAR2(100) UNIQUE NOT NULL
);

-- RELATIONS
CREATE TABLE STUDENT_CLASS (
    STUDENT_ID NUMBER,
    CLASS_ID NUMBER,
    PRIMARY KEY (STUDENT_ID, CLASS_ID)
);

ALTER TABLE STUDENT_CLASS ADD CONSTRAINT FK_SC_STUDENT
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID);

ALTER TABLE STUDENT_CLASS ADD CONSTRAINT FK_SC_CLASS
FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(CLASS_ID);

CREATE TABLE CLASS_SUBJECT_TEACHER (
    CLASS_ID NUMBER,
    SUBJECT_ID NUMBER,
    TEACHER_ID NUMBER,
    PRIMARY KEY (CLASS_ID, SUBJECT_ID, TEACHER_ID)
);

-- ATTENDANCE
CREATE TABLE ATTENDANCE (
    ATTENDANCE_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    CLASS_ID NUMBER,
    ATTENDANCE_DATE DATE NOT NULL,
    SESSION_TYPE VARCHAR2(2) NOT NULL,
    STATUS VARCHAR2(10) NOT NULL,
    LEAVE_REASON VARCHAR2(200),
    APPROVAL_STATUS VARCHAR2(10),
    APPROVED_BY NUMBER,
    CONSTRAINT CHK_SESSION CHECK (SESSION_TYPE IN ('FN','AN')),
    CONSTRAINT CHK_STATUS CHECK (STATUS IN ('Present','Absent','Leave')),
    CONSTRAINT CHK_APPROVAL CHECK (APPROVAL_STATUS IN ('Pending','Approved','Rejected'))
);

-- (You can add remaining FK constraints similarly if needed)

-- =========================
-- END
-- =========================