-- ========================================
-- CSMS DATABASE SETUP FILE
-- ========================================

SET DEFINE OFF;

-- ========================================
-- DROP TABLES (SAFE RE-RUN)
-- ========================================

BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN (
        'ASSIGNMENTS','ATTENDANCE','CLASSES','CLASS_SUBJECT_TEACHER',
        'COUNSELLING','LOGIN_AUDIT','MARKS','PARENT_STUDENT',
        'QUESTION_PAPERS','ROLES','STUDENTS','STUDENT_CLASS',
        'SUBJECTS','SUBMISSIONS','TEACHERS','USERS'
    )) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/
-- ========================================
-- CREATE TABLES (ORDERED PROPERLY)
-- ========================================

-- 1. ROLES
CREATE TABLE ROLES (
    ROLE_ID NUMBER PRIMARY KEY,
    ROLE_NAME VARCHAR2(20) UNIQUE NOT NULL
);

-- 2. USERS
CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    ROLE_ID NUMBER NOT NULL,
    PHONE VARCHAR2(15),
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_USERS_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES ROLES(ROLE_ID)
);

-- 3. CLASSES
CREATE TABLE CLASSES (
    CLASS_ID NUMBER PRIMARY KEY,
    CLASS_NAME VARCHAR2(20) NOT NULL,
    SECTION VARCHAR2(5) NOT NULL,
    ACADEMIC_YEAR VARCHAR2(10) NOT NULL,
    CONSTRAINT UQ_CLASS UNIQUE (CLASS_NAME, SECTION, ACADEMIC_YEAR)
);

-- 4. SUBJECTS
CREATE TABLE SUBJECTS (
    SUBJECT_ID NUMBER PRIMARY KEY,
    SUBJECT_NAME VARCHAR2(100) UNIQUE NOT NULL
);

-- 5. TEACHERS
CREATE TABLE TEACHERS (
    TEACHER_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER UNIQUE,
    QUALIFICATION VARCHAR2(100),
    EXPERIENCE NUMBER CHECK (EXPERIENCE >= 0),
    CONSTRAINT FK_TEACHER_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);

-- 6. STUDENTS
CREATE TABLE STUDENTS (
    STUDENT_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER UNIQUE NOT NULL,
    DOB DATE NOT NULL,
    GENDER VARCHAR2(10),
    CONDUCT VARCHAR2(20),
    CONDUCT_REMARKS VARCHAR2(200),
    CONSTRAINT CHK_GENDER CHECK (GENDER IN ('Male','Female','Other')),
    CONSTRAINT CHK_CONDUCT CHECK (CONDUCT IN ('Excellent','Good','Average','Poor')),
    CONSTRAINT FK_STUDENT_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);

-- 7. CLASS_SUBJECT_TEACHER
CREATE TABLE CLASS_SUBJECT_TEACHER (
    CLASS_ID NUMBER,
    SUBJECT_ID NUMBER,
    TEACHER_ID NUMBER,
    PRIMARY KEY (CLASS_ID, SUBJECT_ID, TEACHER_ID),
    CONSTRAINT FK_CST_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(CLASS_ID),
    CONSTRAINT FK_CST_SUBJECT FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS(SUBJECT_ID),
    CONSTRAINT FK_CST_TEACHER FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS(TEACHER_ID)
);

-- 8. STUDENT_CLASS
CREATE TABLE STUDENT_CLASS (
    STUDENT_ID NUMBER,
    CLASS_ID NUMBER,
    PRIMARY KEY (STUDENT_ID, CLASS_ID),
    CONSTRAINT FK_SC_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID),
    CONSTRAINT FK_SC_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(CLASS_ID)
);

-- 9. PARENT_STUDENT
CREATE TABLE PARENT_STUDENT (
    PARENT_ID NUMBER,
    STUDENT_ID NUMBER,
    RELATION VARCHAR2(50) NOT NULL,
    PRIMARY KEY (PARENT_ID, STUDENT_ID),
    CONSTRAINT FK_PARENT FOREIGN KEY (PARENT_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_STUDENT_PS FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID)
);

-- 10. QUESTION_PAPERS
CREATE TABLE QUESTION_PAPERS (
    QP_ID NUMBER PRIMARY KEY,
    CLASS_ID NUMBER NOT NULL,
    SUBJECT_ID NUMBER NOT NULL,
    EXAM_TYPE VARCHAR2(50),
    EXAM_DATE DATE NOT NULL,
    MAX_MARKS NUMBER NOT NULL,
    CONSTRAINT FK_QP_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(CLASS_ID),
    CONSTRAINT FK_QP_SUBJECT FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS(SUBJECT_ID)
);

-- 11. ASSIGNMENTS
CREATE TABLE ASSIGNMENTS (
    ASSIGNMENT_ID NUMBER PRIMARY KEY,
    CLASS_ID NUMBER,
    SUBJECT_ID NUMBER,
    TITLE VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    DUE_DATE DATE NOT NULL,
    CONSTRAINT FK_ASSIGN_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(CLASS_ID),
    CONSTRAINT FK_ASSIGN_SUBJECT FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS(SUBJECT_ID)
);

-- 12. MARKS
CREATE TABLE MARKS (
    MARK_ID NUMBER PRIMARY KEY,
    STUDENT_ID NUMBER NOT NULL,
    QP_ID NUMBER NOT NULL,
    MARKS_OBTAINED NUMBER CHECK (MARKS_OBTAINED >= 0),
    CONSTRAINT UQ_MARKS UNIQUE (STUDENT_ID, QP_ID),
    CONSTRAINT FK_MARKS_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID),
    CONSTRAINT FK_MARKS_QP FOREIGN KEY (QP_ID) REFERENCES QUESTION_PAPERS(QP_ID)
);

-- 13. SUBMISSIONS
CREATE TABLE SUBMISSIONS (
    SUBMISSION_ID NUMBER PRIMARY KEY,
    ASSIGNMENT_ID NUMBER,
    STUDENT_ID NUMBER,
    SUBMITTED_ON DATE,
    MARKS NUMBER CHECK (MARKS >= 0),
    CONSTRAINT UQ_SUBMISSION UNIQUE (ASSIGNMENT_ID, STUDENT_ID),
    CONSTRAINT FK_SUB_ASSIGN FOREIGN KEY (ASSIGNMENT_ID) REFERENCES ASSIGNMENTS(ASSIGNMENT_ID),
    CONSTRAINT FK_SUB_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID)
);

-- 14. ATTENDANCE
CREATE TABLE ATTENDANCE (
    ATTENDANCE_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    CLASS_ID NUMBER,
    ATTENDANCE_DATE DATE NOT NULL,
    SESSION_TYPE VARCHAR2(2) NOT NULL,
    STATUS VARCHAR2(10) NOT NULL,
    LEAVE_REASON VARCHAR2(200),
    APPROVAL_STATUS VARCHAR2(10),
    APPROVED_BY NUMBER,
    CONSTRAINT CHK_SESSION CHECK (SESSION_TYPE IN ('FN','AN')),
    CONSTRAINT CHK_STATUS CHECK (STATUS IN ('Present','Absent','Leave')),
    CONSTRAINT CHK_APPROVAL CHECK (APPROVAL_STATUS IN ('Pending','Approved','Rejected')),
    CONSTRAINT FK_ATT_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_ATT_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(CLASS_ID),
    CONSTRAINT FK_ATT_APPROVER FOREIGN KEY (APPROVED_BY) REFERENCES USERS(USER_ID)
);

-- 15. COUNSELLING
CREATE TABLE COUNSELLING (
    SESSION_ID NUMBER PRIMARY KEY,
    STUDENT_ID NUMBER,
    COUNSELLOR_ID NUMBER,
    SESSION_DATE DATE,
    NOTES VARCHAR2(500),
    CONSTRAINT FK_COUN_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID),
    CONSTRAINT FK_COUN_USER FOREIGN KEY (COUNSELLOR_ID) REFERENCES USERS(USER_ID)
);

-- 16. LOGIN_AUDIT
CREATE TABLE LOGIN_AUDIT (
    LOG_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    LOGIN_TIME DATE DEFAULT SYSDATE,
    LOGOUT_TIME DATE,
    IP_ADDRESS VARCHAR2(50),
    CONSTRAINT CHK_LOGOUT CHECK (LOGOUT_TIME IS NULL OR LOGOUT_TIME >= LOGIN_TIME),
    CONSTRAINT FK_LOG_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- ========================================
-- END
-- ========================================

COMMIT;
